builds:
  - binary: appbrew
    id: appbrew
    goos:
      - linux
    goarch:
      - amd64
  # notice that we need a separated build for the macos binary only:
  - binary: foo
    id: appbrew-macos
    goos:
      - darwin
    goarch:
      - amd64
signs:
  - signature: "${artifact}"
    ids:
      - appbrew-macos # here we filter the macos only build id
    # you'll need to have gon on PATH
    cmd: gon
    # you can follow the gon docs to properly create the gon.hcl config file:
    # https://github.com/mitchellh/gon
    args:
      - gon.hcl
    artifacts: all